import os
import requests
import re
import sys
from datetime import datetime, timezone, timedelta

# =======================================================
# [1] 사용자 설정 영역
# =======================================================
SAVE_DIR_ROOT = "TIL" 
NOTION_PROPERTY_TITLE = "제목"
NOTION_PROPERTY_DATE = "날짜"
README_FILE = "README.md"

MARKER_START = "<!-- TIL_LIST_START -->"
MARKER_END = "<!-- TIL_LIST_END -->"
TIMEZONE_HOURS = 9 

DEFAULT_README_TEMPLATE = f"""# 📝 My TIL (Today I Learned)

> 매일매일 학습한 내용을 노션에 기록하고, GitHub Actions를 통해 자동으로 동기화하는 저장소입니다. 🚀

<div align="center">
  <img src="https://img.shields.io/badge/Notion-000000?style=for-the-badge&logo=notion&logoColor=white" />
  <img src="https://img.shields.io/badge/GitHub_Actions-2088FF?style=for-the-badge&logo=github-actions&logoColor=white" />
</div>

<br/>

## 📚 TIL 기록 목록

{MARKER_START}
{MARKER_END}

---
<p align="center"><i>Auto-generated by <b>GitHub Actions</b> & <b>Notion API</b></i></p>
"""

# =======================================================
# [2] 시스템 설정 및 API 인증
# =======================================================
NOTION_TOKEN = os.environ.get('NOTION_TOKEN', '')
DATABASE_ID = os.environ.get('NOTION_DATABASE_ID', '')

headers = {
    "Authorization": f"Bearer {NOTION_TOKEN}",
    "Content-Type": "application/json",
    "Notion-Version": "2022-06-28"
}

# =======================================================
# [3] 핵심 기능 함수 모음
# =======================================================
def get_page_blocks(page_id):
    url = f"https://api.notion.com/v1/blocks/{page_id}/children"
    response = requests.get(url, headers=headers)
    
    if response.status_code != 200:
        print(f"⚠️ [경고] 페이지 내용(블록)을 가져오지 못했습니다. ID: {page_id}")
        return []
        
    return response.json().get('results', [])

def extract_text_from_rich_text(rich_text_list):
    content = ""
    for text in rich_text_list:
        plain = text.get('plain_text', '')
        href = text.get('href')
        if href:
            content += f"[{plain}]({href})"
        else:
            content += plain
    return content

def block_to_markdown(block):
    b_type = block.get('type')
    text_blocks = ['paragraph', 'heading_1', 'heading_2', 'heading_3', 'bulleted_list_item', 'numbered_list_item', 'to_do', 'toggle', 'quote', 'callout']
    
    if b_type in text_blocks:
        rich_text = block[b_type].get('rich_text', [])
        content = extract_text_from_rich_text(rich_text)
        
        if b_type == 'paragraph': return content + "\n\n"
        elif b_type == 'heading_1': return f"# {content}\n\n"
        elif b_type == 'heading_2': return f"## {content}\n\n"
        elif b_type == 'heading_3': return f"### {content}\n\n"
        elif b_type == 'bulleted_list_item': return f"- {content}\n"
        elif b_type == 'numbered_list_item': return f"1. {content}\n"
        elif b_type == 'to_do':
            checked = "[x]" if block['to_do'].get('checked') else "[ ]"
            return f"- {checked} {content}\n"
        elif b_type == 'quote': return f"> {content}\n\n"
        elif b_type == 'callout': return f"> 💡 {content}\n\n"
        elif b_type == 'toggle': return f"- ▶ {content}\n"
        
    elif b_type == 'code':
        language = block['code'].get('language', 'text')
        rich_text = block['code'].get('rich_text', [])
        content = extract_text_from_rich_text(rich_text)
        ticks = "`" * 3
        return f"{ticks}{language}\n{content}\n{ticks}\n\n"
        
    elif b_type == 'image':
        url = block['image'].get('file', {}).get('url') or block['image'].get('external', {}).get('url') or ""
        return f"![Image]({url})\n\n"
        
    elif b_type == 'divider': return "---\n\n"
    
    return ""

def sanitize_filename(title):
    clean_name = re.sub(r'[\\/*?:"<>|]', "", title)
    return clean_name.replace(" ", "_")

def save_as_markdown(page, date_str):
    date_str = date_str[:10]
    page_id = page['id']
    
    try:
        title = page['properties'][NOTION_PROPERTY_TITLE]['title'][0]['text']['content']
    except (KeyError, IndexError):
        title = "제목없음"
    
    date_obj = datetime.strptime(date_str, "%Y-%m-%d")
    year, month = date_obj.strftime("%Y"), date_obj.strftime("%m")
    directory = os.path.join(SAVE_DIR_ROOT, year, month)
    os.makedirs(directory, exist_ok=True)
    
    safe_title = sanitize_filename(title)
    filename = os.path.join(directory, f"{date_str}_{safe_title}.md")
    
    blocks = get_page_blocks(page_id)
    md_content = f"# {title}\n\n> 날짜: {date_str}\n> 원본 노션: [링크]({page['url']})\n\n---\n\n"
    
    for block in blocks:
        md_content += block_to_markdown(block)
    
    with open(filename, "w", encoding="utf-8") as f:
        f.write(md_content)
    
    return title, filename

def update_main_readme_by_scanning(reset_mode):
    if not os.path.exists(SAVE_DIR_ROOT):
        print("🔍 [안내] 아직 저장된 TIL 파일이 없어 README 업데이트를 건너뜁니다.")
        return

    files_data = []
    for root, _, files in os.walk(SAVE_DIR_ROOT):
        for file in files:
            if file.endswith(".md"):
                path = os.path.join(root, file)
                date_str = file[:10]
                try:
                    date_obj = datetime.strptime(date_str, "%Y-%m-%d")
                except ValueError:
                    continue
                
                title_part = file[11:-3].replace("_", " ")
                files_data.append({
                    "date": date_obj, "date_str": date_str, 
                    "title": title_part, "path": path
                })

    files_data.sort(key=lambda x: x["date"], reverse=True)

    grouped = {}
    for item in files_data:
        month_key = item["date"].strftime("%Y년 %m월")
        grouped.setdefault(month_key, []).append(item)

    new_content = ""
    for i, (month, items) in enumerate(grouped.items()):
        if i == 0:
            new_content += f"### 💡 {month}\n\n"
            for item in items:
                safe_path = item["path"].replace("\\", "/").replace(" ", "%20")
                date_dot = item['date_str'].replace("-", ".")
                new_content += f"- 🗓️ **{date_dot}** | 🔗 [{item['title']}](./{safe_path})\n"
            new_content += "\n"
        else:
            new_content += f"<details>\n<summary>📂 {month} ({len(items)}개의 기록)</summary>\n\n"
            for item in items:
                safe_path = item["path"].replace("\\", "/").replace(" ", "%20")
                date_dot = item['date_str'].replace("-", ".")
                new_content += f"- 🗓️ **{date_dot}** | 🔗 [{item['title']}](./{safe_path})\n"
            new_content += "\n</details>\n\n"

    if reset_mode == 'true' or not os.path.exists(README_FILE):
        print(f"📄 [안내] 베이스 템플릿으로 {README_FILE} 파일을 (재)생성합니다.")
        with open(README_FILE, "w", encoding="utf-8") as f:
            f.write(DEFAULT_README_TEMPLATE)

    with open(README_FILE, "r", encoding="utf-8") as f:
        readme_text = f.read()

    start_idx = readme_text.find(MARKER_START)
    end_idx = readme_text.find(MARKER_END)

    if start_idx == -1 or end_idx == -1:
        print(f"⚠️ [경고] 기존 README 파일이 꼬여있습니다. 강제로 템플릿을 덮어씁니다.")
        final_content = DEFAULT_README_TEMPLATE.replace(MARKER_START + "\n" + MARKER_END, MARKER_START + "\n" + new_content + MARKER_END)
    else:
        final_content = (
            readme_text[:start_idx + len(MARKER_START)] + 
            "\n" + new_content + 
            readme_text[end_idx:]
        )

    with open(README_FILE, "w", encoding="utf-8") as f:
        f.write(final_content)
    print("✅ [성공] README.md 업데이트 완료!")

# =======================================================
# [4] 메인 실행 함수
# =======================================================
def main():
    fetch_mode = os.environ.get('FETCH_MODE', 'DAILY')
    reset_mode = os.environ.get('RESET_MODE', 'false').lower()
    
    url = f"https://api.notion.com/v1/databases/{DATABASE_ID}/query"
    payload = {}

    if fetch_mode == "ALL":
        print("🌐 [모드: 전체] 노션 표의 모든 데이터를 조회합니다.")
    else:
        kst = timezone(timedelta(hours=TIMEZONE_HOURS))
        target_date = datetime.now(kst).strftime("%Y-%m-%d")
        print(f"📅 [모드: 일간] {target_date} 날짜의 데이터를 조회합니다.")
        payload["filter"] = {
            "property": NOTION_PROPERTY_DATE,
            "date": { "equals": target_date }
        }

    has_more = True
    next_cursor = None
    
    print("\n--- 노션 데이터 추출 시작 ---")
    
    while has_more:
        if next_cursor:
            payload['start_cursor'] = next_cursor
            
        res = requests.post(url, headers=headers, json=payload)
        
        if res.status_code != 200:
            print(f"\n❌ [치명적 에러] 노션 서버가 요청을 거부했습니다.")
            print(f"   - HTTP 응답 코드: {res.status_code}")
            print(f"   - 에러 상세 내용: {res.text}")
            print(f"   👉 해결방법: NOTION_DATABASE_ID가 표의 ID가 맞는지, 권한이 있는지 확인하세요.")
            sys.exit(1)

        data = res.json()
        pages = data.get('results', [])
        
        if not pages:
            print("⚠️ [안내] 조건에 맞는 데이터가 없습니다. (해당 날짜에 작성된 글이 없거나 필터 문제)")
            
        for page in pages:
            page_url = page.get('url', 'Unknown URL')
            try:
                props = page.get('properties', {})
                if NOTION_PROPERTY_DATE not in props:
                    print(f"⏩ [건너뜀] 표에 '{NOTION_PROPERTY_DATE}' 열이 존재하지 않습니다. ({page_url})")
                    continue
                
                date_data = props[NOTION_PROPERTY_DATE].get('date')
                if not date_data:
                    print(f"⏩ [건너뜀] '{NOTION_PROPERTY_DATE}' 칸이 비어있습니다. ({page_url})")
                    continue
                
                page_date = date_data.get('start')
                title, filepath = save_as_markdown(page, page_date)
                print(f"✅ [저장 완료] {filepath}")
                
            except Exception as e:
                print(f"❌ [에러 발생] 글을 처리하는 중 문제가 발생했습니다: {e} ({page_url})")
                continue
        
        has_more = data.get('has_more', False)
        next_cursor = data.get('next_cursor')

    print("--- 노션 데이터 추출 종료 ---\n")
    update_main_readme_by_scanning(reset_mode)

if __name__ == "__main__":
    main()
